### PR TITLE
Fix decoding of SRPs in vault data

### LINKED ISSUE #4: The link to How to Copy Your Vault Data doesn't work
Hi dear developers,

The link(https://metamask.helpscoutdocs.com/article/22-how-to-copy-your-vault-data) says page not found/not public.  Can you please fix this issue? Thanks!

### LINKED ISSUE #27: Decrypter giving a bunch of numbers
Decrypter is now giving a bunch of numbers instead of the actual seed. Tested on multiple active and new metamask's.

### LINKED ISSUE #32: decryptor giving some numbers instead of seed phrase
long story short, I am trying to decrypt a metamask vault from a brave browser file.

I have the {"data":"... string and the decryptor works with my password, but it does not give me my mnemonic phrase, rather it gives a bunch of small numbers (lower than 200)  separated by ,

this is my output (numbers changed):
[{"type":"HD Key Tree","data":{"mnemonic":[108,97,110,115,145,111,110,35,108,111,98,115,116,101,114,32,102,101,129,32,102,114,111,103,32,99,104,111,105,99,101,32,98,97,99,104,111,108,111,114,32,112,97,116,99,104,32,119,117,115,116,32,112,97,112,101,114,32,185,115,111,108,97,116,101,42,107,112,105,115,111,100,101,32,97,117,116,118,179,110],"numberOfAccounts":1,"hdPath":"m/44'/60'/0'/0"}},{"type":"Ledger Hardware","data":{"hdPath":"m/44'/60'/0'","accounts":[],"accountDetails":{},"bridgeUrl":"https://metamask.github.io/eth-ledger-bridge-keyring","implementFullBIP44":false}}]

### LINKED ISSUE #36: decryptor is broken
Hello can you fix the metamask vault decryptor please ? The decryptor give numbers instead of words and I need it ASAP !! Thanks you very much

### PR DESCRIPTION
**Pull request by mcmire**
We recently made a change in the extension to how keyring data is
encrypted so that the SRP is encoded. This means that when decrypting
the vault data the SRP must be decoded as well.

Fixes #27.
Fixes #32.
Fixes #36.
Fixes #4.

## Manual testing

1. Run `npm install`.
2. Run `npm run build` to create a build.
3. Run `open index.html` (macOS) or just open `index.html` in your browser.
4. Assuming you have the extension installed locally and you've had the extension installed for some time, copy your vault data as per the [guide in Zendesk](https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data).
6. Paste it into the text area in the vault decryptor.
7. You should see the decrypted vault data appear along with your SRP.
8. Remove the extension from your browser.
9. Reinstall the extension and import your existing account or create a new one.
10. Copy your vault data again as per the guide above.
11. Paste it into the text area in the vault decryptor.
12. You should see the decrypted vault data appear along with your SRP.

### CODE REVIEW

File: app/root.js [hunk 1]
```diff
@@ -87,26 +95,34 @@ AppRoot.prototype.render = function () {
...
-    console.log('Decrypted!', decrypted)
-    this.setState({ decrypted })
-  })
-  .catch((reason) => {
-    console.error(reason)
-    this.setState({ error: 'Problem decoding vault.' })
-  })
+    .then((keyringsWithEncodedMnemonic) => {
+      const keyringsWithDecodedMnemonic = keyringsWithEncodedMnemonic.map(keyring => {
+        if ('mnemonic' in keyring.data) {
```
Comment (mcmire) [inline app/root.js:103]: Not all kinds of keyrings have a `mnemonic` property.

File: app/root.js [hunk 2]
```diff
@@ -6,6 +6,14 @@ const passworder = require('browser-passworder')
 
 module.exports = connect(mapStateToProps)(AppRoot)
 
+function decodeMnemonic(mnemonic) {
+  if (typeof mnemonic === 'string') {
```
Comment (mcmire) [inline app/root.js:10]: This should handle existing accounts as well as any new accounts that were created after the aforementioned PR in the extension.

**Review by kumavis — APPROVED** [review]
